"""init

Revision ID: 1e2369053c96
Revises: 
Create Date: 2025-04-23 10:54:36.218960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2369053c96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('secondname', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_category', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("\n                (user_id IS NULL AND name_category IN (\n                    'Зарплата', 'Продукты', 'Кафе', \n                    'Досуг', 'Здоровье', 'Транспорт'\n                )) \n                OR \n                (user_id IS NOT NULL)\n            ", name='system_categories_check'),
    sa.CheckConstraint("\n                NOT (\n                    user_id IS NULL \n                    AND name_category NOT IN (\n                        'Зарплата', 'Продукты', 'Кафе', \n                        'Досуг', 'Здоровье', 'Транспорт'\n                    )\n                )\n            ", name='only_six_system_categories'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_sum', sa.Numeric(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transit')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
